agents:

  PDM4ARSpaceship:

    state:

      x: -8.0

      y: -8.0

      psi: 0.26179938779     # ≈ 15°

      vx: 0.0

      vy: 0.0

      dpsi: 0.0



    goal:

      type: static

      state:

        x: 8.0

        y: 8.0

        psi: 0.0

        vx: 0.0

        vy: 0.0

        dpsi: 0.0

      pos_tolerance: 0.5

      dir_tolerance: 0.5

      vel_tolerance: 1.0



    color: blue





planets:

  Namek:

    center: [0.0, 0.0]

    radius: 0.04



 



  Alderaan:

    center: [-4.0, 5.0]

    radius: 0.18

  

  Krypton:

    center: [-2.0, 5.0]

    radius: 0.7



 





asteroids: {}



boundary:

  corners:

    - [-11, -11]

    - [-11, 11]

    - [11, 11]

    - [11, -11]

    - [-11, -11]



seed: 98