agents:
  PDM4ARSpaceship:
    state:
      x: -8.0
      y: -8.0
      psi: 0.26179938779     # ≈ 15°
      vx: 0.0
      vy: 0.0
      dpsi: 0.0

    goal:
      type: static
      state:
        x: 8.0
        y: 8.0
        psi: 0.0
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.5
      dir_tolerance: 1.0
      vel_tolerance: 1.0
      #add_land_space: 0.0 
      #arms_length: 1.3 
      #offset: 1.3

    color: blue


planets:
  Namek:
    center: [0.0, 0.0]
    radius: 0.04

 

  Alderaan:
    center: [-4.0, 5.0]
    radius: 0.18
  
  Krypton:
    center: [-2.0, 5.0]
    radius: 0.7
  
  ciao:
    center: [-1.0, 5.0]
    radius: 0.18
  
  gatto:
    center: [2.0, 4.0]
    radius: 0.7
  
  pene:
    center: [-3.0, -4.0]
    radius: 1.0
  
  sbur:
    center: [0.0, -5.0]
    radius: 0.6
  
  

 


asteroids: {}

boundary:
  corners:
    - [-17, -17]
    - [-17, -17]
    -  [-17, -17]
    - [-17, -17]
    -  [-17, -17]

seed: 98
